export const app = {
    asciiAnimationInitialized: false,
    asciiCharData: [],
    asciiEnabled: true,
    tuiMode: "command",
    standbyOpen: false,
    results: [],
    selected: 0,
    lyricsObserver: null,
    syncIconTimer: null,
    djObserver: null,
    djMode: false,
    djPanelOpen: false,
    djPrevPane: null,
    commandHistory: [],
    commandHistoryIndex: -1,
    playlistPanelOpen: false,
    playlists: [],
    playlistSongs: [],
    playlistSongsTotal: 0,
    playlistSongsFetchToken: 0,
    playlistSongsFetchTimer: null,
    selectedPlaylist: 0,
    selectedSong: 0,
    activePane: "playlist",
    helpPanelOpen: false,
    aboutPanelOpen: false,
    themePanelOpen: false,
    onboardingPanelOpen: false,
    onboardingStage: "commands",
    onboardingShowAllThemes: false,
    lyricsPanelOpen: false,
    visualizerOpen: false,
    lyricsLoadToken: 0,
    lyricsActiveIndex: -1,
    lyricsActiveLoaderIndex: -1,
    searchPanelOpen: false,
    searchResults: [],
    searchSelected: 0,
    searchFocus: "input",
    searchQuery: "",
    searchAutocomplete: "",
    searchFetchToken: 0,
    searchDebounce: null,
    searchBound: false,
    lyricsCache: { uri: "", lines: [], synced: false, provider: "", instrumental: false, error: "" },
    lyricsBound: false,
    lyricsSyncInterval: null,
    cachedLyricsRows: [],
    cachedLyricsLoaders: [],
    jamRole: null,
    jamPin: null,
    jamToken: null,
    jamIntervalId: null,
    jamBarPrevHidden: null,
    jamLastAppliedUri: null,
    themesFeedPromise: null,
    playlistListScrollRaf: null,
    songListScrollRaf: null,
    songScrollAnimRaf: null,
    navRafPending: false,
    playlistNavLastAt: 0,
    playlistNavFast: false
};

// Returns true if any panel except lyrics or standby is open
export function isAnyPanelOpen() {
    return app.standbyOpen || Object.keys(app).some(k => k.endsWith("PanelOpen") && k !== "lyricsPanelOpen" && app[k]);
}
