name: FA

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  approve:
    if: >
      github.event.issue.pull_request &&
      github.event.comment.body == '!fa' &&
      github.event.comment.user.login == 'SkenSMasteR'
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          gh api \
            repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}/reviews \
            -f event=APPROVE \
            -f body="Force approved by @${{ github.event.comment.user.login }}"
